### PR TITLE
Fixes the pattern encoder ability to craft

### PR DESCRIPTION
**Pull request by tyra314**
This might not be the best solution, but at least, it works...
This actually fixes two problems.

1) "Pattern terminal recipe output gets cleared when you can't craft the
   item.", which is part of #2

To fix that, I call getAndUpdateOutput() in the
ContainerPatternTerm::onSlotChange, when it seems appropriate.

2) The pattern terminal doesn't craft at all. The problem is that
SlotCrafting::onTake internally expects the inventory to be castable
to InventoryCraftResult. However, it gets passed an AppEngInternalInventory.
To fix that, I replaced the cOut type with InventoryCraftResult.

### CODE REVIEW

**Comment by yueh** [comment]
This can be very dangerous as well as a breaking change.

Pattern terminals try to avoid crafting an item, should there already be one inside the network. In this case it will simply extract it. For example without enough materials, it will still allow to extract a preexisting item and continue with the following pattern using that particular item.

The other important requirement is, that the pattern terminal is using fake slots. Thus you only need 1 diamond to create the pattern for a diamond block. Under no circumstances can it allow that the fake slots are used as real inventory to dupe items.

**Comment by tyra314** [comment]
Maybe I should have split those issues at least into different commits. However, I try to walk you through the changes and describe, why I think it fixes the issues and not introduce the problems mentioned by yueh.

The easier part is [this line](https://github.com/GuntherDW/Applied-Energistics-2/pull/10/files#diff-17b35f60af54618cbfa13a6b20d91edeR497) and the following three lines. Whenever a slot is changed on the client side, we call the method `getAndUpdateOutput` also on the client side. The called function looks at the crafting "area" and tries to identify a valid crafting pattern, if so, it adds the result into the crafting result slot. These are all fake items. When the player clicks on the crafting result item, he picks up the fake item, but this will trigger a `PacketPatternSlot` send to the server and handled by the `ContainerPatternTerm::craftOrGetItem`. If it can be crafted (or supplied through the ME Network) the player keeps the fake item. If not, the item will disappear.I wasn't able, to find the code path that controls this, but that's what I see while testing it. However, as the crafting result slot was changed -remember the player picked up the item - `onSlotChanged` is called, which I changed. In the end, either way, a new fake item is placed in the crafting result slot.

The rest of the patch just handles with `SlotCrafting::onTake` requiring an `InventoryCraftResult` as input. So I switched out the container, where the crafting inventory is stored. In the `ContainerPatternTerm::craftOrGetItem`, where the `SlotCrafting::onTake` is called, the crafting ingredients are pulled before the call. If they can't be pulled, the function is never called. Thus, I think, it doesn't break the restraints to use this container there.

**Comment by yueh** [comment]
It probably works. `getAndUpdateOutput()` is probably fine to call. That is just the GUI itself being pretty messing and needing some rework.

My main concern is using an `InventoryCraftResult` as it is a vanilla/forge class and probably not aware of fake slots. Some moddev will hook into it, cancel the default behaviour for their recipe and handle it with their own packets/server side logic under the assumption "It can never be a fake slot". It just waits to break.

My intuition simply says we are trading a current minor bug with a future major bug instead of actually fixing or at least identifying the underlying issue. Maybe I am wrong and it will never happen. But that could just mean being lucky.

**Comment by tyra314** [comment]
I see your point. However, with the same argument you can rule out using any minecraft class.
But I certainly would go down that path, if you want to, but I'd need some advice than.

Just a different thought: Maybe just going the opposite direction and just remove the code to craft inside the pattern terminal. That never made sense to me anyways?

ps: Shall I split up the PR, or even make it against AE2/rv5-1.12 ?

**Comment by yueh** [comment]
It should be easier to test it with PR for the main repo. Currently I just guess about it, but cannot really test it. I just want to raise the awareness for potential issues. As long as somebody remembers, there was a discussion about a dupe bug like 4 months ago and a potential cause for it, I would be happy.

Removing the crafting from pattern terminals would certainly not be good. It would making patterns way more tedious. Pretty much something like
1. Open Crafting Terminal to craft ingredients
2. Put the items into our inventory or throw them back into the network (and forget which ones)
3. Open pattern terminal, paste the recipe, encode
4. Place the pattern into your inventory
5. Paste the next pattern, realise you need 2 of the inputs for the the upcoming tier. Close it again.
6. Back to the crafting terminal
   1. Or walk half a mile to an interface, drop the pattern and go back.
7. Craft the needed stuff for the next tier with a crafting terminal or maybe request them via pattern termial
8. Rinse repeat.

So yeah. Pretty tedious. Currently you can encode all patterns and craft every intermediate product in a single terminal. And just in case, no we cannot simply encode a pattern provided by JEI without having the actual items. There should be some issues with more detailed infos. If you are interested, I should be able to dig them up. Or worst case have to write it down again.

**Comment by tyra314** [comment]
Reopened against official repo.

**Pull request closed without merging**
