### PR TITLE
Use IItemHandler instead of IInventory internally

### PR DESCRIPTION
**Pull request by fscan**
Not a real pull request .. I just want some comments on the progress so far.

It compiles, and the basic things seem to work.  Its a very big change, but i see no way of splitting it up without breaking compilation.

The imports need to be cleaned up too.

### CODE REVIEW

**Comment by fscan** [comment]
@yueh, can you please have a look at this? I want to know if i've done something obviously stupid or if this is the right direction.

**Comment by yueh** [comment]
At first glance it does not look bad.

There are a few minor style things. Like

* Unused Imports
* Formatting sometimes a bit screwed (e.g. ContainerQuartzKnife.java#getStackInSlot(), Spaces instead of tabs etc)
* Method names are always camelCased (there is a `GetCell()` no idea from where)
* We no longer use punch cards, it is ok to write `inventory` and not `inv`

The `IAEItemFilter` is kinda nice. But I am not 100% convinced about it.Besides patterns and cells, I also cannot immediately remember any filter, which could be shared across multiple inventories. But that is mostly related to the next point.

I am not keen on the `IItemHandlerModifiable`. It is more like a `IItemHandlerBypassEverySafeGuard`.
The only addition is allowing direct access to a slot via `setStackInSlot()`. The issue here is that we have to handle everything externally. E.g. copy stacks for fake slots, limit to 1 for fake slots, filter slots via something like `IAEItemFilter`.
I might miss some cases currently, but the normal insert/extract would be totally fine to handle filtering, ensure we copy the stack when needed, set the stacksize correctly and so on. Also nothing prevents an `ItemHandler` from setting a fake slot to something and simply returning the item as it is.
At least it is something to consider.

`WrapperInvItemHandler` and `WrapperChainedItemHandler` might already be provided by forge. At least the chained exists. I only fail to remember, if it might behave a bit differently.
Similar with `ItemHandlerUtil`

The explicit `return false` for `hasCapability()` might cause trouble in the feature (copypasta). It would be an idea to have a root class with something like `this.getInternalInventory != null` or an `Optional`. Or even better stop annoucing a tile without an iventory as one with an inventory.
Also never forget to call `super.(hasCap|getCap)`. Otherwise people will whine, because they cannot attach every cap out there to every tile entity.

Mostly unrelated, `InventoryAdaptor` should probably go away. It is our own `IItemHandler` before they existed.

**Comment by fscan** [comment]
> The IAEItemFilter is kinda nice. But I am not 100% convinced about it.Besides patterns and cells, I also cannot immediately remember any filter, which could be shared across multiple inventories. But that is mostly related to the next point.

Yeah, the readonly/writeonly filter is used in a few places and could possibly be used in some more.  Maybe a instanceof filter may be used in a few places. Also, i'm not married to the name, it's more like a access control than a filter.

>I am not keen on the IItemHandlerModifiable. It is more like a IItemHandlerBypassEverySafeGuard.
The only addition is allowing direct access to a slot via setStackInSlot(). The issue here is that we have to handle everything externally. E.g. copy stacks for fake slots, limit to 1 for fake slots, filter slots via something like IAEItemFilter.

One problem i came across is that the forge wrappers (combine, range, etc) only work on IItemHandlerModifiable. My view is that it's only for internal use. When exposed externally it should always be IItemHandler. Note that filters ignore setStackInSlot().

>WrapperInvItemHandler and WrapperChainedItemHandler might already be provided by forge. At least the chained exists. I only fail to remember, if it might behave a bit differently.
Similar with ItemHandlerUtil

I added ItemHandlerUtil to add often used functionality which is not provided by forge's ItemHandlerHelper ... i really miss c# extension methods or at least c/c++ style free functions.

>Mostly unrelated, InventoryAdaptor should probably go away. It is our own IItemHandler before they existed.

The nice thing about it is that it can insert into a inventory, not just a specific slot. But i can extract that part of the functionality in a helper function (eg ItemHelperUtil)

Regarding unused imports, i mostly ignored them for now to ease rebasing.

**Comment by yueh** [comment]
> Yeah, the readonly/writeonly filter is used in a few places and could possibly be used in some more. Maybe a instanceof filter may be used in a few places. Also, i'm not married to the name, it's more like a access control than a filter.

As said, the idea is nice. But the use cases might be a bit limited currently. There are also a couple of variations possible. Like keep the `AppEngInternalInventory` as main itemhandler and allow a filter as constructor parameter.

> One problem i came across is that the forge wrappers (combine, range, etc) only work on IItemHandlerModifiable. My view is that it's only for internal use. When exposed externally it should always be IItemHandler. Note that filters ignore setStackInSlot().

Hm. I suppose it might make it easier to avoid extracting stuff first to just replace a slot.

> I added ItemHandlerUtil to add often used functionality which is not provided by forge's ItemHandlerHelper ... i really miss c# extension methods or at least c/c++ style free functions.

Just to be sure. Based on personal experience Forge likes to put static helper classes everywhere, without any common naming conventions. Of course also not documented anywhere. So it is easy to miss already provided functionality.

> The nice thing about it is that it can insert into a inventory, not just a specific slot. But i can extract that part of the functionality in a helper function (eg ItemHelperUtil)

I forgot about the slotless approach (or better I want to forget that `IItemHandlers` are slotaware...
It might be an idea to keep it, but just reduce it to a wrapper around `ItemHandler` and of course the more advanced internal me inventories. But like drop the player adaptor (just wrap the forge itemhandler for it)

> Regarding unused imports, i mostly ignored them for now to ease rebasing.

Just to mention it. The code analysis will start screaming once it is merged back into the main repo.

**Comment by fscan** [comment]
> The explicit return false for hasCapability() might cause trouble in the feature (copypasta). It would be an idea to have a root class with something like this.getInternalInventory != null or an Optional. Or even better stop annoucing a tile without an iventory as one with an inventory.

Youre probably talking about the controller and the energy acceptor? The real problem there is with the class hierarchy, because every powered tile is automatically an inventory. Maybe i can split up the tree without too much duplication now that IInventory is gone.
But youre right, checking for null on getInternalInventory in AEBaseInvTile would be better.

>Also never forget to call super.(hasCap|getCap). Otherwise people will whine, because they cannot attach every cap out there to every tile entity.

Did you find a place where it is missing? Or just general advice?

**Comment by yueh** [comment]
> Youre probably talking about the controller and the energy acceptor? The real problem there is with the class hierarchy, because every powered tile is automatically an inventory. Maybe i can split up the tree without too much duplication now that IInventory is gone.
But youre right, checking for null on getInternalInventory in AEBaseInvTile would be better.

In particular these. If my memory is not completely wrong, it might also apply to QNB rings or the storage cpus. But these are a bit special. I might be completely wrong, but iirc they (can) store any overflow from the crafting process and only returning it when done or something else actually requests them. So there might be a extremely rare case of someone piping the overflow out directly... If that ever happpens... But if, it would be fine as long as it only applies to the overflow. Which of course makes pretty much no sense to do ever...
So we could consider every possible regression, or simply dump it...

> Did you find a place where it is missing? Or just general advice?

For whatever reason I remember seeing like 2 or 3 cases with the explicitly disabled ones... I might be completely wrong here of course. I know there is the networktool, but that is an item and I do not want to even think about itemstacks and caps as it is pretty unstable.
So if in doubt, just as general advice.

**Comment by fscan** [comment]
Did a little bit of testing/fixing. Stuff seems to work, there are some ui sync issues (eg condenser), but they also exist in the 1.10 version.
Any plans on using this? For that matter, are you communicating with guy doing the other AE2 port? I'm a bit lost on how to go forward with this.

**Comment by yueh** [comment]
Yes, we want to use it. It probably just needs some further testing as it is quite a large change. As well as a final pass over the code once you are happy with it, to avoid the obvious issues.

I finally also did recall why I did not like using `IItemHandlerModifiable` for most things. It is mostly about these inventories not really being inventories. They are just collections of items and only need `contains`, an `iterator` and some way to set the content, which could just be passing an array or list to the constructor or a `setContents` depending on being immutable or mutable.
The reason for it is that most if  them are used as filter. Thus there is never a need for extract or insert. But it needs a fast `contains` (no array contains with O(n)), which is not offered by an `IItemHandler` directly. So we still have to maintain a separate class for it. 

Abusing `IIventory` was probably not the best idea, but it at least fit a bit better than an `IItemHandler` in these cases. (Due to being similar to an array). But certainly nothing we have to consider for this PR. Just keeping it in mind.

Of course there are still a couple of real inventories like the upgrade slots. But they have absolutely no interactions with other machines, which is the idea behind `IItemHandler`. Just some a few slots inside the GUI.

I have no idea about the other port currently. But I do not see any intention to work together and port AE2 itself. It just appears as a trying to release something as fast as possible and therefore split the community for some personal gains. I can fully understand, if you do not want to participate in that kind of "stuff".

**Comment by fscan** [comment]
I ended up using IItemHandlerModifiable mostly because although SlotItemHandler pretends to work with IItemHandler but really doesn't. It would be possible to implement setStackInSlot via extract all + insert new, but i'm not sure this is semantically equivalent in all cases.
For basic array access IItemHandlerModifiable is mostly the same as IInventory, with the plus side that the interface is smaller (i removed a lot of boilerplate code). 
I wouldn't really worry about speed here. I honestly think that at the n values we are talking about you will never go faster than ArrayList (memory efficiency,  cache locality). The internal ME Inventory is a different beast altogether, but we are not using IItemHandler for this.

**Comment by yueh** [comment]
It should be fine. Just does not fit perfectly as insert/extract is a (very) slightly dubious. A `UnsupportedOperationException` would fit. But just waiting to explode randomly. Thus just returning the itemstack on insert or an empty on extract would be fine.

The effort to have a fitting interface and all the gui slots is probably way more work than it is actually worth.
And in the worst case need an adaptor for `IItemHandler` at the end for some reason, we could not avoid.

I was mostly thinking about the internal ME inventory for speed. Like it would be nice to avoid keeping multiple instances for the GUI, internal filters and so on. But we have the advantage of using our own itemstacks internally and they deduplicate NBT tags other approaches could get quite nasty when considering it is a multilayered filter and each could have it's own nbt copy with 1MB data.

Sharing the collection for the filter and GUI will most likely not work well. Especially as the internal filters would ideally return a subset of potential targets instead of trying every inventory (Cannot recall the exact approach currently). It might also eliminate the two pass approach. But then again it can easily contain a few thousand cache keys for itemstack with different NBT data. Maintain them over multiple layers each aggregating the ones directly below them. It sounds nice on paper, but the additional memory requirement might not be worth. Plus ensuring that it is always consistent (chunk unloads...)

There are still more other issue related to the inventory causing some performance issues. But it is already way better compared to 1.7.10. A threadsafe ME inventory would be nice to avoid having to do a full copy for the crafting calculations. But then it has to deal with changing values while it still calculates the tree. A copy on wright approach might be better, but has to be a two way one. So a change inside the actual cannot propagate into the crafting inventory at all as well as the crafting one never ever performing anything on the underlying one. (Unrelated, just throwing ideas around)

**Comment by fscan** [comment]
I was away for a week, will redo the patch for 1.12 in the official repository.

**Comment by yueh** [comment]
I would highly appreciate it. Hopefully a rebase just works or at least not many conflicts.
It would also go through our CI servers, thus way easier to test it without having to manually merge and build it locally.

**Comment by fscan** [comment]
Tried to rebase, got a headache ... should be less work now that i know how to do it anyway.

**Comment by yueh** [comment]
I am sorry about it. It might be worth a try to squash it into a single commit. So it does not have to rebase 7 single commits, including having to reapply the removed code in later commits.

**Comment by fscan** [comment]
Ok, yeah, squashing helped a lot. The remaining conflicts where mostly because of formatting and imports. Will make a new request shortly.

**Pull request closed without merging**
