### PR TITLE
Fixes Grinder

### PR DESCRIPTION
**Pull request by tyra314**
For one, this adds the tileentities back in the Block constructors.

It also fixes the Grinder not working in case of an input
ItemStack with size equal to one.
The important bit here is the sequence of instructions.
With the <=1.10 representation of empty ItemStacks using null
the old ordering was fine. However, whenever an ItemStack gets
shrinked to zero, its internal Item gets replaced, thus you
have to make a copy before shrinking.

Additionally using ItemStack::shrink instead of grow with
negative value. I can't stand such things D:

### CODE REVIEW

**Comment by tyra314** [comment]
I bet this also applies to the 1.11 branch, but I haven't tested that.

**Comment by GuntherDW** [comment]
While the grinder does indeed have a bug that it voids the item if you input a single one, the Tile Entity stuff isn't required because those are set in ApiBlocks.java in their respective build statements.

I might throw those back into the block classes once I've decided on what I'm going to do in terms of TE registration, doing it this way without removing them from ApiBlocks.java serves no real purpose?

**Comment by yueh** [comment]
As already stated, the TE should be set during registration. If they don't work, fix the bug there instead of moving code around hoping it might fix it.

There are other ways to to do it. But if everything else like rendering, models, etc are defined in one place, then TEs should be no exception. E.g. have something like `appeng.basics.grindstone.{Api,Block,Tile,Model,Init,...}`

IIRC there was simply no `shrink` with the initial 1.11 port.

**Comment by tyra314** [comment]
> IIRC there was simply no shrink with the initial 1.11 port.

That wasn't meant offensive. I had it in my hands anyway, so I changed it to the less mentally consuming alternative.

**Comment by yueh** [comment]
Oh, I did not consider it offensive in any way. Either it was not there in 1.11 or I completely overlooked it (maybe no mappings). It is just nice to get a hint about a better fitting method.

**Comment by tyra314** [comment]
Okay, same question here: Shall I adapt the PR here or should I make a new one (without the tile registration) against AE2/rv-1-12?

**Comment by yueh** [comment]
Feel free to make a new PR for the official repo. It would also be a nice test for the CI systems.

**Comment by tyra314** [comment]
Reopened against official repo: https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/2962

**Pull request closed without merging**
